name: Gather menu link

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  gather:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up dependencies
        run: npm ci

      - name: Extract the link
        run: npm run start

      - name: Commit updated links
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Added a new menu link'